# Generated by Django 4.2.3 on 2024-03-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_word_annotation_alter_word_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Word_Example",
                to="core.word",
            ),
        ),
    ]
